### ISSUE TITLE
Filtering Problem

### ISSUE THREAD

**Issue by KhayyamNosrati** [websemantics/masonry-plus#1]
Hi,
I used your plugin in my project, but it toggle sometimes.
I mean if i click on a filter for second time, layout changes into inline vertically and multiple "data-filter"s doesn't work.
May I know how to fix them?
Thank You for your nice job.

**Comment by websemantics** [comment]
I'm not surprised, .. you're the first person who used it other than myself, 
Here's the project I am using the plugin in, http://websemantics.github.io/pyrocms-cheatsheet/ for an example use,
Other than that, I would need an example, JSFiddle?, or a way to re-create the issue,
And thank you for kind words and feedback,

**Comment by KhayyamNosrati** [comment]
Good to hear that.. thank you for the reply.. this is the example you
wanted https://jsfiddle.net/KhayyamNosrati/e1dzq4op/ if you click on design
tab and after a second re-click on it, it changes the layout and you would
see the result.

Good Day :-)

**Comment by websemantics** [comment]
That was a though one, .. I had to debug the original plugin and finally found the problem,

I've overridden a function from the original plugin, `measureColumns`  so it should work now, v1.0.1

Will try to connect with the original plugin authors so they get the issue fixed and I can then remove the extra code,

Thanks for the helpful code demo for the bug,

**Comment by KhayyamNosrati** [comment]
Appreciate your support.. Thank you very much
I see you did a wonderful job again.. sure, I appreciate that.
And Thank you again for debugging it.

Good Day :-)
