### ISSUE TITLE
IE Browser Comapatiblity

### ISSUE THREAD

**Issue by KhayyamNosrati** [websemantics/masonry-plus#2]
Hi again, Hope you are doing well 
I found another issue.

The plugin does not work properly with IE. I tried Internet Explorer 11, and when I load the page which I have created, the plugin doesn't work and masonry layout is not proper, and it effects other contents as well..

Would You Please make it cross-browser
Thank You in advance again :-)
Have a Good day!

**Comment by websemantics** [comment]
Did you test if the issue was from the original plugin or is it specific for the plus new features, `filter` and `shuffle`?

**Comment by KhayyamNosrati** [comment]
The function you have override "measureColumns" creates the issue in IE as
I checked.
When I remove it, the plugin works fine in IE.

**Comment by KhayyamNosrati** [comment]
I finally found the solution! 
The original plugin author got the this [issue ](https://github.com/desandro/masonry/commit/ab600d05f768d94d36027ddc2925c608791f873b) fixed before..
now the whole thing works fine for IE as well.
Thank You
Have a Good day!

**Comment by websemantics** [comment]
I've looked at the [issue](https://github.com/desandro/masonry/commit/ab600d05f768d94d36027ddc2925c608791f873b) fix, the code of 'measureColumns' isn't different from the current masonry-plus 1.0.1 code!!

**Comment by KhayyamNosrati** [comment]
check lines 67-76 in "masonry-plus 1.0.1 ".. there are small changes.

**Comment by KhayyamNosrati** [comment]
check lines 67-76 in "masonry-plus 1.0.1 " and compare with the [issue](https://github.com/desandro/masonry/commit/ab600d05f768d94d36027ddc2925c608791f873b).. there are small changes.

**Comment by websemantics** [comment]
1- masonry-plus 1.0.1 (67-76)

``` javascript
// if columnWidth is 0, default to outerWidth of first item
if ( !this.columnWidth ) {
/* var firstItem = this.items[0] old code */
var firstItem = this.items.find(function(item) {return !item.isIgnored})
var firstItemElem = firstItem && firstItem.element
// columnWidth fall back to item of first element
this.columnWidth = firstItemElem && getSize( firstItemElem ).outerWidth ||
    // if first elem has no width, default to size of container
    this.containerWidth
}
```

2- masonry.js (64-69)

``` javascript
// if columnWidth is 0, default to outerWidth of first item
if ( !this.columnWidth ) {
    var firstItem = this.items[0];
    var firstItemElem = firstItem && firstItem.element;
    // columnWidth fall back to item of first element
    this.columnWidth = firstItemElem && getSize( firstItemElem ).outerWidth ||
    // if first elem has no width, default to size of container
    this.containerWidth;
}
```

3- Changes,

This,

``` javascript
var firstItem = this.items[0]
```

Changed to, 

``` javascript
var firstItem = this.items.find(function(item) {return !item.isIgnored})
```

As per [issue #1](https://github.com/websemantics/masonry-plus/issues/1), 

Or am I missing something more obvious here?

**Comment by KhayyamNosrati** [comment]
![1](https://cloud.githubusercontent.com/assets/20792731/19822616/0c9a76da-9d82-11e6-81cc-df221d14f474.png)

`var firstItemElem = this.items[0].element;`

`this.columnWidth = this.columnWidth || getSize( firstItemElem ).outerWidth;`
These lines are removed.

`var firstItem = this.items[0];`

`var firstItemElem = firstItem && firstItem.element;`
and these are added BEFORE(out of) if statement.

You can changed above, in the jsfiddle [issue #1](https://jsfiddle.net/KhayyamNosrati/e1dzq4op/) while running it with Internet Explorer, then compare with masonry-plus 1.0.1.
 And Thank You for all your friendly respond and support! :-)

**Comment by websemantics** [comment]
You're correct, .. my mistake! ... I compared with the latest release, [4.1.1](https://github.com/desandro/masonry/blob/v4.1.1/masonry.js), not the [issue](https://github.com/desandro/masonry/commit/ab600d05f768d94d36027ddc2925c608791f873b) you pointed out, 

Still wondering why you had to revert back to an older release to get your code working! But as long as it solved your problem I guess :)
